version: '3.8'

services:
  web:
    build: .
    command: gunicorn travel_sphere.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=travel_sphere.settings.production
      - DJANGO_SECRET_KEY=travelsphere-docker-prod-secret-99128374
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  celery_worker:
    build: .
    command: celery -A travel_sphere worker -l info
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=travel_sphere.settings.production
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

  celery_beat:
    build: .
    command: celery -A travel_sphere beat -l info
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=travel_sphere.settings.production
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
