# Generated by Django 5.0.6 on 2026-09-01 05:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_class', models.CharField(default='bi-check-circle', help_text='Bootstrap Icon class, e.g. bi-wifi, bi-water', max_length=50)),
                ('category', models.CharField(choices=[('GENERAL', 'General Services'), ('WELLNESS', 'Spa & Wellness'), ('FOOD', 'Dining & Drinks'), ('ROOM', 'In-Room Perks'), ('BUSINESS', 'Business & Events')], default='GENERAL', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HotelChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hotels/chains/')),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HotelProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('star_rating', models.PositiveSmallIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=4)),
                ('property_type', models.CharField(choices=[('HOTEL', 'Luxury Hotel'), ('RESORT', 'Beach / Mountain Resort'), ('BOUTIQUE', 'Boutique Heritage Inn'), ('VILLA', 'Private Villa Estate'), ('APARTMENT', 'Serviced Apartment')], default='HOTEL', max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('overview', models.TextField()),
                ('check_in_time', models.TimeField(default='14:00:00')),
                ('check_out_time', models.TimeField(default='11:00:00')),
                ('cancellation_policy', models.TextField(default='Free cancellation up to 48 hours before check-in.')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='hotels/properties/%Y/%m/')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('rating_average', models.DecimalField(decimal_places=2, default=4.8, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('amenities', models.ManyToManyField(blank=True, related_name='hotels', to='hotels.amenity')),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='hotels.hotelchain')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='destinations.city')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='destinations.destination')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hotels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hotel Properties',
                'ordering': ['-is_featured', '-rating_average', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HotelMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('RO', 'Room Only / European Plan'), ('BB', 'Bed & Breakfast (Continental)'), ('HB', 'Half Board (Breakfast + Dinner)'), ('FB', 'Full Board (All 3 Meals)'), ('AI', 'All Inclusive (Unlimited Meals & Drinks)')], max_length=20)),
                ('price_per_person', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=8)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='hotels.hotelproperty')),
            ],
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='hotels/gallery/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('is_primary', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='hotels.hotelproperty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('STANDARD', 'Standard Room'), ('DELUXE', 'Deluxe Room'), ('SUPERIOR', 'Superior Suite'), ('EXECUTIVE_SUITE', 'Executive Suite'), ('PRESIDENTIAL', 'Presidential Suite'), ('VILLA', 'Private Luxury Villa'), ('CHALET', 'Mountain Chalet')], default='DELUXE', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('max_adults', models.PositiveIntegerField(default=2)),
                ('max_children', models.PositiveIntegerField(default=1)),
                ('bed_type', models.CharField(default='1 King Bed or 2 Twin Beds', max_length=100)),
                ('room_size_sqm', models.PositiveIntegerField(default=35)),
                ('base_price_per_night', models.DecimalField(decimal_places=2, default=Decimal('120.00'), max_digits=10)),
                ('weekend_surcharge_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('total_rooms_count', models.PositiveIntegerField(default=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/rooms/%Y/%m/')),
                ('amenities', models.ManyToManyField(blank=True, related_name='room_types', to='hotels.amenity')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='hotels.hotelproperty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('available_rooms', models.PositiveIntegerField()),
                ('booked_rooms', models.PositiveIntegerField(default=0)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='hotels.roomtype')),
            ],
            options={
                'verbose_name_plural': 'Room Inventories',
                'ordering': ['date'],
                'unique_together': {('room_type', 'date')},
            },
        ),
    ]
