# Generated by Django 5.0.6 on 2026-09-01 05:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('meals_included', models.CharField(default='Breakfast', help_text='e.g. Breakfast, Lunch, Dinner', max_length=100)),
                ('accommodation', models.CharField(blank=True, help_text='Hotel / Resort name or type', max_length=200)),
                ('overnight_city', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon_class', models.CharField(default='bi-compass', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Tour Categories',
            },
        ),
        migrations.CreateModel(
            name='ItineraryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('is_optional', models.BooleanField(default=False)),
                ('extra_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('day_itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tours.dayitinerary')),
            ],
            options={
                'ordering': ['start_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TourGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('languages_spoken', models.CharField(help_text='Comma-separated languages, e.g., English, Spanish, French', max_length=255)),
                ('experience_years', models.PositiveIntegerField(default=3)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tour_guide_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('code', models.CharField(help_text='Unique SKU code, e.g. TSP-EUR-001', max_length=30, unique=True)),
                ('subtitle', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('duration_days', models.PositiveIntegerField(default=3)),
                ('duration_nights', models.PositiveIntegerField(default=2)),
                ('min_group_size', models.PositiveIntegerField(default=1)),
                ('max_group_size', models.PositiveIntegerField(default=20)),
                ('difficulty_level', models.CharField(choices=[('EASY', 'Easy / Leisure'), ('MODERATE', 'Moderate Walking'), ('STRENUOUS', 'Strenuous / Trekking'), ('EXTREME', 'Extreme Adventure')], default='EASY', max_length=20)),
                ('base_price_adult', models.DecimalField(decimal_places=2, default=Decimal('199.00'), max_digits=10)),
                ('base_price_child', models.DecimalField(decimal_places=2, default=Decimal('99.00'), max_digits=10)),
                ('single_supplement_price', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='tours/featured/%Y/%m/')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_all_inclusive', models.BooleanField(default=False)),
                ('instant_confirmation', models.BooleanField(default=True)),
                ('cancellation_policy', models.TextField(default='Full refund up to 7 days before departure. 50% refund up to 48 hours.')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('booking_count', models.PositiveIntegerField(default=0)),
                ('rating_average', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_packages', to=settings.AUTH_USER_MODEL)),
                ('assigned_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='tours.tourguide')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='tours.tourcategory')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_packages', to='destinations.destination')),
            ],
            options={
                'ordering': ['-is_featured', '-booking_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourInclusionExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=255)),
                ('is_included', models.BooleanField(default=True, help_text='True for Included, False for Excluded')),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions_exclusions', to='tours.tourpackage')),
            ],
        ),
        migrations.CreateModel(
            name='TourFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='tours.tourpackage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalSurcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Summer High Season, Christmas Surcharge', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.15'), help_text='e.g. 1.20 for 20% surge', max_digits=4)),
                ('fixed_surcharge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_surcharges', to='tours.tourpackage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dayitinerary',
            name='tour_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='tours.tourpackage'),
        ),
        migrations.CreateModel(
            name='TourPackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CLOTHING', 'Clothing & Footwear'), ('DOCUMENTS', 'Travel Documents & ID'), ('GEAR', 'Trekking / Sports Gear'), ('MEDICATION', 'Health & Medication'), ('ELECTRONICS', 'Electronics & Adapters')], default='General', max_length=50)),
                ('item_name', models.CharField(max_length=150)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_list', to='tours.tourpackage')),
            ],
        ),
        migrations.CreateModel(
            name='TourDepartureDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departure_date', models.DateField(db_index=True)),
                ('return_date', models.DateField()),
                ('total_slots', models.PositiveIntegerField(default=20)),
                ('booked_slots', models.PositiveIntegerField(default=0)),
                ('adult_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('child_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_guaranteed_departure', models.BooleanField(default=True)),
                ('is_sold_out', models.BooleanField(default=False)),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='tours.tourpackage')),
            ],
            options={
                'ordering': ['departure_date'],
                'unique_together': {('tour_package', 'departure_date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='dayitinerary',
            unique_together={('tour_package', 'day_number')},
        ),
    ]
