# Generated by Django 5.0.6 on 2026-09-01 05:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(help_text='e.g. EK (Emirates), SNCF, GREY', max_length=20, unique=True)),
                ('transport_type', models.CharField(choices=[('FLIGHT', 'Flight'), ('TRAIN', 'Train'), ('BUS', 'Intercity Luxury Bus'), ('PRIVATE_TRANSFER', 'Private Transfer / Chauffeur'), ('FERRY', 'Ferry / Cruise')], default='FLIGHT', max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='transports/operators/')),
                ('customer_support_phone', models.CharField(blank=True, max_length=30)),
                ('rating', models.DecimalField(decimal_places=2, default=4.5, max_digits=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StationStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(help_text='IATA (e.g. JFK, LHR) or Station code', max_length=20)),
                ('station_type', models.CharField(choices=[('FLIGHT', 'Flight'), ('TRAIN', 'Train'), ('BUS', 'Intercity Luxury Bus'), ('PRIVATE_TRANSFER', 'Private Transfer / Chauffeur'), ('FERRY', 'Ferry / Cruise')], default='FLIGHT', max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='destinations.city')),
            ],
            options={
                'ordering': ['city__name', 'name'],
                'unique_together': {('code', 'station_type')},
            },
        ),
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route_code', models.CharField(help_text='e.g. EK-201, TGV-9840', max_length=50)),
                ('distance_km', models.PositiveIntegerField(default=500)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=120)),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_routes', to='transports.stationstop')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='transports.transportoperator')),
                ('origin_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_routes', to='transports.stationstop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('departure_time', models.DateTimeField(db_index=True)),
                ('arrival_time', models.DateTimeField()),
                ('vehicle_identifier', models.CharField(default='Boeing 777-300ER', help_text='Aircraft / Train type or Bus Reg', max_length=100)),
                ('is_direct', models.BooleanField(default=True)),
                ('stops_summary', models.CharField(default='Non-stop', max_length=255)),
                ('luggage_allowance', models.CharField(default='1 Check-in (23kg) + 1 Cabin (7kg)', max_length=150)),
                ('meal_service_included', models.BooleanField(default=True)),
                ('wifi_available', models.BooleanField(default=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='transports.transportroute')),
            ],
            options={
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='SeatClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_type', models.CharField(choices=[('ECONOMY', 'Economy Class'), ('PREMIUM_ECONOMY', 'Premium Economy'), ('BUSINESS', 'Business Class'), ('FIRST_CLASS', 'First Class'), ('SLEEPER', 'Sleeper Berth'), ('AC_TIER_1', '1st AC'), ('AC_TIER_2', '2nd AC'), ('AC_TIER_3', '3rd AC')], default='ECONOMY', max_length=30)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=10)),
                ('total_capacity', models.PositiveIntegerField(default=180)),
                ('booked_count', models.PositiveIntegerField(default=0)),
                ('refundable', models.BooleanField(default=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_classes', to='transports.transportschedule')),
            ],
            options={
                'unique_together': {('schedule', 'class_type')},
            },
        ),
    ]
