# Generated by Django 5.0.6 on 2026-09-01 05:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_tax_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_agency_payouts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_bookings_count', models.PositiveIntegerField(default=0)),
                ('new_users_registered', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DynamicPriceAdjustmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjusted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjustment_factor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('trigger_reason', models.CharField(max_length=255)),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_adjustments', to='tours.tourpackage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(default='DIRECT', max_length=100)),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='tours.tourpackage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('search_query', models.CharField(max_length=255)),
                ('category_filter', models.CharField(blank=True, max_length=100)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
